### ISSUE TITLE
FeatureFlagSetLD fails to delete when referencing a non-existing secret

### ISSUE THREAD

**Issue by acbodine** [razee-io/FeatureFlagSetLD#173]
**Describe the bug**
Creating a FeatureFlagSetLD with a reference to a secret that doesn't exist results in the inability to delete the FeatureFlagSetLD resource.

**To Reproduce**
1. Create test namespace `kubectl create ns test`
2. Prepare FeatureFlagSetLD that references a non-existent secret:
```sh
$ cat test-ffsld.yaml 
apiVersion: deploy.razee.io/v1alpha2
kind: FeatureFlagSetLD
metadata:
  name: test-ffsld
  namespace: test
spec:
  sdkKeyRef:
    valueFrom:
      secretKeyRef:
        name: ld-bogus-key
        key: ld-sdk-key
```
3. Create the invalid FeatureFlagSetLD
```sh
$ kubectl create -f test-ffsld.yaml
```
4. Try and delete the FeatureFlagSetLD
```sh
$ kubectl delete -f test-ffsld.yaml --wait=false
```
5. Observe that the deletionTimestamp is set, and the featureflagset controller never removes the finalizer `client.featureflagset.deploy.razee.io`:
```
$ kubectl -n test get ffsld -o yaml
apiVersion: v1
items:
- apiVersion: deploy.razee.io/v1alpha2
  kind: FeatureFlagSetLD
  metadata:
    annotations:
      deploy.razee.io/data-hash: 06675bbcec328ebdac7259e879483f91a296b6de
    creationTimestamp: 2021-01-20T21:12:46Z
    deletionGracePeriodSeconds: 0
    deletionTimestamp: 2021-01-20T21:13:25Z
    finalizers:
    - client.featureflagset.deploy.razee.io
    generation: 2
    name: test-ffsld
    namespace: test
    resourceVersion: "53804004"
    selfLink: /apis/deploy.razee.io/v1alpha2/namespaces/test/featureflagsetsld/test-ffsld
    uid: e35552fd-3dd0-4ab2-a4e3-c67ed1096acf
  spec:
    sdkKeyRef:
      valueFrom:
        secretKeyRef:
          key: ld-sdk-key
          name: ld-bogus-key
  status:
    deploy.razee.io/finalizer-cleanup: running
    razee-logs:
      error:
        44d223594d33d3498918ed73d5de3ee1ea3b2f88: 404 - {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"secrets
          \"ld-bogus-key\" not found","reason":"NotFound","details":{"name":"ld-bogus-key","kind":"secrets"},"code":404}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Expected behavior**
Non-existent dependencies for a resource should not prevent its deletion. When I request the deletion of the FeatureFlagSetLD the corresponding razee controller should remove its finalizer and allow deletion to finish.

**Screenshots**
N/A

**Kubernetes Version (kubectl version):**
```sh
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T17:05:32Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.15+IKS", GitCommit:"434eee04daa6546e81c6d3240ffe6bcdf642cf1d", GitTreeState:"clean", BuildDate:"2020-11-25T21:25:42Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
We did not test this, but are concerned this issue may exist in other Razee CRDs. Please check this.

**Comment by alewitt2** [comment]
looks like a bug with FeatureFlagSet. If it fails to find a valid sdkKey https://github.com/razee-io/FeatureFlagSetLD/blob/master/src/FeatureFlagSetLDController.js#L217, it doesnt know how to cleanup, so it just keeps failing. Need to add a try/catch to better handle these cases, i will look into this more tmrw.
